[pytest]
addopts = -v -s --alluredir=allure-results --clean-alluredir
markers =
    get_booking_id: booking handler for get booking_id
    get_booking_by_id: booking handler for get booking by id
    create_booking: booking handler for create
    update_booking: booking handler fur update
    partial_update_booking: partial booking handler fur update
    delete_booking: booking handler handler for delete
log_cli = true
log_cli_level = INFO
testpaths = tests